### PR TITLE
Improve admin form documentation.

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: None.

* Post that caused this: https://groups.google.com/d/msg/islandora/TSgtRxrxwaM/r1MzH9S0BAAJ

# What does this Pull Request do?

De-opaquifies the Video Solution Pack configuration. 

# What's new?

Refactored the configuration form to explain the relationships between the various options. Referred to datastreams consistently. Made some fields invisible unless they are needed. Improved descriptions.

# How should this be tested?

Test the form - it should work exactly as before. 
Ask someone who's not familiar with the code to read the options and explain what they do. 

# Additional Notes:

* Does this change require documentation to be updated? **Yep - the Wiki will need its screenshot and wording updated.*
* Does this change add any new dependencies? **No.**
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?  **No.**
* Could this change impact execution of existing code? **No.**

# Interested parties
@Islandora/7-x-1-x-committers, @jonathangreen (latest maintainer), @bondjimbond (does this help with the situation that you encountered in the forum post?)

### CODE REVIEW

**Review by bondjimbond — APPROVED** [review]
Looks good. I like that you moved the max file size nearer the top; it's hard to spot otherwise. Everything looks pretty clear.

**Comment by DiegoPino** [comment]
@bondjimbond would you mind merging since you tested the steps? The sooner the better so we don't interfere with AUDIT process. Thanks

**Comment by DiegoPino** [comment]
@bondjimbond ping

**Comment by rosiel** [comment]
psst... @bondjimbond  @Islandora/7-x-1-x-committers

**Comment by bondjimbond** [comment]
@rosiel @DiegoPino Ack, sorry - for some reason the notifications for these never hit me! I hang my head.

**Pull request merged**
