### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by bryjbrown**
Reverts Islandora/islandora_solution_pack_video#146

### CODE REVIEW

**Comment by DonRichards** [comment]
Should it be reverted or just modified?

**Comment by bondjimbond** [comment]
@DonRichards I think best choice is probably to revert, then make a new PR with your branch and modifications. Does that sound good?

**Comment by bryjbrown** [comment]
@DonRichards Since we can't modify your previous PR, its probably best to revert and then add all the changes as a new PR. Realistically you could do it either way, but having all the changes in one commit makes it easier to compare to the 7.x-1.12 changelog.

**Comment by DonRichards** [comment]
Just wondering. No objection.

**Review by DonRichards — APPROVED** [review]

**Pull request merged**
