### PR TITLE
Update screenshot

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2231

# What does this Pull Request do?

Updates the screenshot

# How should this be tested?

Look at screenshot, maybe compare to vagrant?

# Additional Notes:

Example:
* Does this change require documentation to be updated? It is documentation
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@whikloj @DonRichards ping. Question, how do you feel about this making use of https://github.com/Islandora/islandora_videojs/pull/48/files new screen shot (see at https://github.com/DonRichards/islandora_videojs/blob/a28c7f7321715fe302bf938ca9d2fd00ce4b8cb7/README.md) == means could share the same screenshot?  Or are there differences there?

**Comment by DiegoPino** [comment]
@whikloj @DonRichards ping again? @rosiel what do you think about https://github.com/Islandora/islandora_solution_pack_video/pull/144#issuecomment-390218362?

**Review by rosiel — APPROVED** [review]
No, we don't require 100% duplicate removal of screenshots, that's not reasonable to expect. This PR is perfectly fine and I'm sorry it got stalled for so long.

**Comment by whikloj** [comment]
@DiegoPino I don't have a preference if you want to reuse that screenshot, that is fine with me.

**Comment by rosiel** [comment]
@whikloj This looks ready to merge - Can you please make a release PR?

**Comment by rosiel** [comment]
@whikloj @DiegoPino  just holding out for a release PR.

**Comment by DiegoPino** [comment]
@rosiel I'm ok with how it is. This is approved. We just need a release one. But if not, then we can simply live without this?

**Comment by whikloj** [comment]
sorry folks, finishing this up right now

**Pull request merged**
