### PR TITLE
ISLANDORA-2159 Remove references to legacy variable.

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-2159)

# What does this Pull Request do?

Cleans up a legacy variable, so as to not confuse people into thinking that features that don't exist, exist. 

# What's new?

Removes islandora_video_retain_original and its references (except to uninstall).

# How should this be tested?

Look for outstanding references to this variable in the codebase?

# Additional Notes:

* Does this change require documentation to be updated? Yes - text has been changed in the Wiki, but the screenshot has not yet been updated to remove the variable.
* Could this change impact execution of existing code? Do you have an extension that uses this variable? Then you may want to create an admin form for it. No code in the release will be affected.

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by whikloj** [comment]
@rosiel just wondering we should just add an update hook to remove the variable if it exists and then you could remove it from the `*.install` file too?

**Comment by rosiel** [comment]
@whikloj what do we usually do?

**Comment by whikloj** [comment]
🤣 what do we do with variables we set and then **never** use...I don't know. I'd say you are blazing a new trail here.

I am fine leaving it in the `*.install` for now. But eventually we'd need to remove it from that file too and as part of that I would add an `hook_update_N()` to ensure it is deleted. 

So you can do that now or someone can do it later. Your call.

**Review by whikloj — APPROVED** [review]
👍

**Comment by DiegoPino** [comment]
"Usual" way is to leave the removal to an eventual Module removal. So *.instal ++ also from me. Good pull

**Comment by whikloj** [comment]
@DiegoPino I just thought that it could be a long time until we stop supporting this module, so we would have to keep that useless variable in the `*.install` file until then. This way its gone once they update. I prefer this way to reduce stuff I have to remember 😄 

If you feel strongly we can go back, otherwise I'm good to start the 24 hour wait.

**Comment by DiegoPino** [comment]
you mean the 23 hour wait? 😄 go for it!

**Comment by rosiel** [comment]
Updated the wiki's screenshot.

**Pull request merged**
